# Generated by Django 5.0.6 on 2024-06-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.FileField(blank=True, null=True, upload_to='appointment_payments/'),
        ),
    ]
