# Generated by Django 5.0.6 on 2024-06-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_failed_logins_serviceproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='failed_logins',
            field=models.IntegerField(default=0),
        ),
    ]
