# Generated by Django 5.0.6 on 2024-06-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_is_locked_alter_user_failed_logins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='failed_logins',
            new_name='failedLogins',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_locked',
            new_name='isLocked',
        ),
    ]
