# Generated by Django 5.0.6 on 2024-06-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_failed_logins_user_failedlogins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment',
            field=models.FileField(upload_to='files/appointment_payments/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='files/service_images/'),
        ),
    ]
