# Generated by Django 5.0.6 on 2024-06-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment',
            field=models.FileField(blank=True, null=True, upload_to='files/appointment_payments/'),
        ),
    ]
