# Generated by Django 5.0.6 on 2024-06-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_appointment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
